// Generated by CoffeeScript 1.8.0
var Hapi, Inert, Vision, fs, server;

Hapi = require('hapi');

Vision = require('vision');

Inert = require('inert');

fs = require('fs');

server = new Hapi.Server();

server.connection({
  port: process.env.PORT || 5000
});

server.register(Vision, function(err) {
  if (err) {
    throw err;
  }
  server.views({
    engines: {
      jade: require('jade')
    },
    relativeTo: __dirname,
    path: 'views',
    isCached: false
  });
  return server.register(Inert, function(err) {
    if (err) {
      throw err;
    }
    require("./routes/routes.js")(server);
    return server.start(function() {
      return console.log("\nServer running on " + server.info.uri + "\n");
    });
  });
});
