// Generated by CoffeeScript 1.8.0
var Joi, ViewModel, csrf, fs, getModels, jsonfile, models, schema;

Joi = require('joi');

csrf = require('csrf-lite');

fs = require('fs');

jsonfile = require('jsonfile');

schema = {};

models = {};

getModels = function() {
  var models_path;
  console.log("getting models");
  models_path = "./models/";
  return fs.readdirSync(models_path).forEach(function(filename, i) {
    var data, name;
    data = jsonfile.readFileSync(models_path + filename);
    name = filename.split(".")[0];
    return models[name] = data;
  });
};

getModels();

ViewModel = function(modelname) {
  this.title = "";
  this.pageTitle = "";
  this.errors = [];
  if (modelname) {
    this.setAsModel(modelname);
  }
  return this;
};

ViewModel.prototype.setAsModel = function(modelname) {
  if (!modelname) {
    return;
  }
  this.model = models[modelname];
  if (!this.model) {
    console.log("" + modelname + " doesn't exist in models path:" + models_path);
  }
  return this;
};

ViewModel.prototype.scheme = function(name, scheme) {
  if (!name) {
    return;
  }
  schema[name] = scheme;
  return this;
};

ViewModel.prototype.validate = function(name, payload) {
  console.log("ViewModel::validate not built.");
  return this;
};

ViewModel.prototype.updateModels = function() {
  getModels();
  return this;
};

ViewModel.prototype.send = function() {
  this.token = csrf();
  return this;
};

module.exports = ViewModel;
