// Generated by CoffeeScript 1.8.0
var ViewModel;

ViewModel = require('../viewmodel.js');

module.exports = function(server) {
  server.state("_token", {
    ttl: 60 * 60 * 1000,
    isSecure: false,
    isHttpOnly: true,
    encoding: 'base64json'
  });
  server.route({
    method: 'GET',
    path: '/',
    handler: {
      view: {
        template: 'index',
        context: {}
      }
    }
  });
  server.route({
    method: 'GET',
    path: '/shop',
    handler: {
      view: {
        template: 'shop',
        context: {}
      }
    }
  });
  server.route({
    method: 'GET',
    path: '/customize',
    handler: function(req, reply) {
      var viewmodel;
      viewmodel = new ViewModel("customize");
      console.log(viewmodel);
      return reply.view("customize", viewmodel.send()).state("_token", viewmodel.token);
    }
  });
  server.route({
    method: 'GET',
    path: '/faq',
    handler: {
      view: {
        template: 'faq',
        context: {}
      }
    }
  });
  server.route({
    method: 'GET',
    path: '/contact',
    handler: {
      view: {
        template: 'contact',
        context: {}
      }
    }
  });
  server.route({
    method: 'GET',
    path: '/favicon.ico',
    handler: function(request, reply) {
      return reply.file("./favicon.ico");
    }
  });
  server.route({
    method: 'GET',
    path: '/images/{file*}',
    handler: {
      directory: {
        path: 'public/images',
        listing: true
      }
    }
  });
  server.route({
    method: 'GET',
    path: '/css/{file*}',
    handler: {
      directory: {
        path: 'public/css',
        listing: true
      }
    }
  });
  server.route({
    method: 'GET',
    path: '/scripts/{file*}',
    handler: {
      directory: {
        path: 'public/scripts',
        listing: true
      }
    }
  });
  return server.route({
    method: 'GET',
    path: '/{file*}',
    handler: {
      directory: {
        path: 'public',
        listing: true
      }
    }
  });
};
