// Generated by CoffeeScript 1.8.0
var ViewModel, defaults, _defaults;

_defaults = defaults = {
  title: ""
};

ViewModel = function(options) {
  var key, value, _i, _len;
  if (options == null) {
    options = defaults;
  }
  for (value = _i = 0, _len = options.length; _i < _len; value = ++_i) {
    key = options[value];
    this[key] = value;
  }
  return this;
};

ViewModel.prototype.setDefaults = function(override) {
  defaults = override;
};

ViewModel.prototype.add = function(key, obj) {
  this[key] = obj;
  return this;
};
